// Static demo data for the hosted showcase build (NEXT_PUBLIC_DEMO=1).
//
// This mirrors backend/awsco/demo/fixtures.py so the deployed dashboard can
// render the exact sample scan WITHOUT a backend — the hosted site is a
// showcase, not a live tool. Real scans always run locally against the API.
import type { Finding, RegionInfo, ScanResult } from "./types";

const ACCOUNT = "123456789012";
const arn = (service: string, region: string, id: string) =>
  `arn:aws:${service}:${region}:${ACCOUNT}:demo/${id}`;

// Findings, pre-sorted by monthly savings desc (same order the CLI prints).
const FINDINGS: Finding[] = [
  {
    id: "rds.idle:prod-leftover-db",
    check_id: "rds.idle",
    title: "Idle RDS instance prod-leftover-db (db.m5.large)",
    description: "RDS instance had 0 connections over 7 days.",
    service: "rds",
    region: "us-east-1",
    resource_arn: arn("rds", "us-east-1", "prod-leftover-db"),
    resource_id: "prod-leftover-db",
    monthly_savings_usd: 123.12,
    severity: "high",
    confidence: "medium",
    cli_fix_command:
      "aws rds stop-db-instance --region us-east-1 --db-instance-identifier prod-leftover-db",
    fix_destructive: false,
    evidence: { instance_class: "db.m5.large", engine: "postgres", max_connections_7d: 0 },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "ebs.unattached:vol-0abc1234",
    check_id: "ebs.unattached",
    title: "Unattached EBS volume vol-0abc1234 (500 GB, gp2)",
    description: "500 GB gp2 volume in available state.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "vol-0abc1234"),
    resource_id: "vol-0abc1234",
    monthly_savings_usd: 50.0,
    severity: "high",
    confidence: "high",
    cli_fix_command: "aws ec2 delete-volume --region us-east-1 --volume-id vol-0abc1234",
    fix_destructive: true,
    evidence: {
      size_gb: 500,
      volume_type: "gp2",
      availability_zone: "us-east-1a",
      create_time: "2026-01-23T00:00:00Z",
    },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "ec2.stopped-billed-ebs:i-0abcdef123456",
    check_id: "ec2.stopped-billed-ebs",
    title: "EC2 'old-staging' stopped for 187d, still billing $42.00/mo for EBS",
    description: "Stopped EC2 with 2 EBS volumes (350 GB total) still billing.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "i-0abcdef123456"),
    resource_id: "i-0abcdef123456",
    monthly_savings_usd: 42.0,
    severity: "high",
    confidence: "high",
    cli_fix_command:
      "aws ec2 terminate-instances --region us-east-1 --instance-ids i-0abcdef123456",
    fix_destructive: true,
    evidence: { instance_type: "m5.xlarge", days_stopped: 187, volume_ids: ["vol-1", "vol-2"] },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "nat.idle:nat-0a1b2c3d4e5f6",
    check_id: "nat.idle",
    title: "Idle NAT gateway nat-0a1b2c3d4e5f6",
    description: "Idle NAT gateway in us-east-1, 0 bytes over 7d.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "nat-0a1b2c3d4e5f6"),
    resource_id: "nat-0a1b2c3d4e5f6",
    monthly_savings_usd: 32.4,
    severity: "high",
    confidence: "high",
    cli_fix_command:
      "aws ec2 delete-nat-gateway --region us-east-1 --nat-gateway-id nat-0a1b2c3d4e5f6",
    fix_destructive: false,
    evidence: {
      bytes_out_7d: 0,
      vpc_id: "vpc-aaa",
      subnet_id: "subnet-bbb",
      create_time: "2026-03-30T00:00:00Z",
    },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "nat.idle:nat-99887766",
    check_id: "nat.idle",
    title: "Idle NAT gateway nat-99887766",
    description: "Idle NAT gateway in eu-west-1, 412 bytes over 7d.",
    service: "ec2",
    region: "eu-west-1",
    resource_arn: arn("ec2", "eu-west-1", "nat-99887766"),
    resource_id: "nat-99887766",
    monthly_savings_usd: 32.4,
    severity: "high",
    confidence: "high",
    cli_fix_command:
      "aws ec2 delete-nat-gateway --region eu-west-1 --nat-gateway-id nat-99887766",
    fix_destructive: false,
    evidence: { bytes_out_7d: 412, vpc_id: "vpc-ccc" },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "ebs.gp2-to-gp3:vol-prod001",
    check_id: "ebs.gp2-to-gp3",
    title: "Migrate gp2 → gp3: vol-prod001 (1000 GB)",
    description: "gp3 is 20% cheaper at equal performance.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "vol-prod001"),
    resource_id: "vol-prod001",
    monthly_savings_usd: 20.0,
    severity: "high",
    confidence: "high",
    cli_fix_command:
      "aws ec2 modify-volume --region us-east-1 --volume-id vol-prod001 --volume-type gp3",
    fix_destructive: false,
    evidence: { size_gb: 1000, iops: 3000 },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "lb.unused:staging-old-alb",
    check_id: "lb.unused",
    title: "Unused application load balancer staging-old-alb",
    description: "ALB has no registered targets.",
    service: "elb",
    region: "us-east-1",
    resource_arn: arn("elb", "us-east-1", "staging-old-alb"),
    resource_id: "staging-old-alb",
    monthly_savings_usd: 16.2,
    severity: "medium",
    confidence: "high",
    cli_fix_command:
      "aws elbv2 delete-load-balancer --region us-east-1 --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/staging-old-alb/x",
    fix_destructive: false,
    evidence: { lb_type: "application", reason: "no registered targets" },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "ebs.gp2-to-gp3:vol-prod002",
    check_id: "ebs.gp2-to-gp3",
    title: "Migrate gp2 → gp3: vol-prod002 (500 GB)",
    description: "gp3 is 20% cheaper at equal performance.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "vol-prod002"),
    resource_id: "vol-prod002",
    monthly_savings_usd: 10.0,
    severity: "medium",
    confidence: "high",
    cli_fix_command:
      "aws ec2 modify-volume --region us-east-1 --volume-id vol-prod002 --volume-type gp3",
    fix_destructive: false,
    evidence: { size_gb: 500 },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "ebs.snapshot-old:snap-deadbeef01",
    check_id: "ebs.snapshot-old",
    title: "Old EBS snapshot snap-deadbeef01 (412d old, 200 GB)",
    description: "Snapshot is 412 days old.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "snap-deadbeef01"),
    resource_id: "snap-deadbeef01",
    monthly_savings_usd: 10.0,
    severity: "medium",
    confidence: "medium",
    cli_fix_command:
      "aws ec2 delete-snapshot --region us-east-1 --snapshot-id snap-deadbeef01",
    fix_destructive: true,
    evidence: { size_gb: 200, age_days: 412 },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "ebs.unattached:vol-0def5678",
    check_id: "ebs.unattached",
    title: "Unattached EBS volume vol-0def5678 (100 GB, gp3)",
    description: "100 GB gp3 volume in available state.",
    service: "ec2",
    region: "us-west-2",
    resource_arn: arn("ec2", "us-west-2", "vol-0def5678"),
    resource_id: "vol-0def5678",
    monthly_savings_usd: 8.0,
    severity: "medium",
    confidence: "high",
    cli_fix_command: "aws ec2 delete-volume --region us-west-2 --volume-id vol-0def5678",
    fix_destructive: true,
    evidence: { size_gb: 100, volume_type: "gp3", create_time: "2026-05-11T00:00:00Z" },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "logs.no-retention:legacy-cluster",
    check_id: "logs.no-retention",
    title: "Log group '/aws/ecs/legacy-cluster' has no retention policy",
    description: "Log group grows indefinitely.",
    service: "logs",
    region: "us-west-2",
    resource_arn: arn("logs", "us-west-2", "legacy-cluster"),
    resource_id: "/aws/ecs/legacy-cluster",
    monthly_savings_usd: 7.2,
    severity: "medium",
    confidence: "high",
    cli_fix_command:
      "aws logs put-retention-policy --region us-west-2 --log-group-name '/aws/ecs/legacy-cluster' --retention-in-days 30",
    fix_destructive: false,
    evidence: { stored_bytes: 257698037760, stored_gb: 240.0 },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "logs.no-retention:old-cron",
    check_id: "logs.no-retention",
    title: "Log group '/aws/lambda/old-cron' has no retention policy",
    description: "Log group grows indefinitely. Set retention to 30 days.",
    service: "logs",
    region: "us-east-1",
    resource_arn: arn("logs", "us-east-1", "old-cron"),
    resource_id: "/aws/lambda/old-cron",
    monthly_savings_usd: 4.5,
    severity: "low",
    confidence: "high",
    cli_fix_command:
      "aws logs put-retention-policy --region us-east-1 --log-group-name '/aws/lambda/old-cron' --retention-in-days 30",
    fix_destructive: false,
    evidence: { stored_bytes: 161061273600, stored_gb: 150.0 },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "eip.unused:eipalloc-aaaa",
    check_id: "eip.unused",
    title: "Unused Elastic IP 52.12.34.56",
    description: "Allocated EIP not associated. AWS bills $0.005/hour.",
    service: "ec2",
    region: "us-east-1",
    resource_arn: arn("ec2", "us-east-1", "eipalloc-aaaa"),
    resource_id: "eipalloc-aaaa",
    monthly_savings_usd: 3.6,
    severity: "low",
    confidence: "high",
    cli_fix_command: "aws ec2 release-address --region us-east-1 --allocation-id eipalloc-aaaa",
    fix_destructive: false,
    evidence: { public_ip: "52.12.34.56", domain: "vpc" },
    detected_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "eip.unused:eipalloc-bbbb",
    check_id: "eip.unused",
    title: "Unused Elastic IP 52.78.90.12",
    description: "Allocated EIP not associated.",
    service: "ec2",
    region: "eu-west-1",
    resource_arn: arn("ec2", "eu-west-1", "eipalloc-bbbb"),
    resource_id: "eipalloc-bbbb",
    monthly_savings_usd: 3.6,
    severity: "low",
    confidence: "high",
    cli_fix_command: "aws ec2 release-address --region eu-west-1 --allocation-id eipalloc-bbbb",
    fix_destructive: false,
    evidence: { public_ip: "52.78.90.12" },
    detected_at: "2026-06-01T00:00:00Z",
  },
];

const REGIONS_SCANNED = ["us-east-1", "us-west-2", "eu-west-1"];

// Mirrors server._demo_regions(): common enabled regions + a few not-activated.
export const demoRegions: RegionInfo[] = [
  ...[
    "us-east-1", "us-east-2", "us-west-1", "us-west-2",
    "eu-west-1", "eu-west-2", "eu-central-1",
    "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1",
    "ca-central-1", "sa-east-1",
  ].map((name) => ({ name, opt_in_status: "opt-in-not-required", enabled: true })),
  ...["ap-east-1", "me-south-1", "af-south-1"].map((name) => ({
    name,
    opt_in_status: "not-opted-in",
    enabled: false,
  })),
].sort((a, b) => a.name.localeCompare(b.name));

/** The full demo scan, or a region-filtered slice (mirrors the server's
 *  demo-mode region filter so the dashboard's switcher behaves the same). */
export function demoScan(regions?: string[] | null): ScanResult {
  const wanted = regions && regions.length ? new Set(regions) : null;
  const findings = wanted ? FINDINGS.filter((f) => wanted.has(f.region)) : FINDINGS;
  const scanned = wanted
    ? REGIONS_SCANNED.filter((r) => wanted.has(r))
    : REGIONS_SCANNED;
  return {
    scan_id: "demo-scan",
    account_id: ACCOUNT,
    started_at: "2026-06-01T00:00:00Z",
    finished_at: "2026-06-01T00:00:12Z",
    regions_scanned: scanned,
    findings,
    errors: [],
    is_demo: true,
  };
}
